### ISSUE TITLE
Details on text extraction?

### ISSUE THREAD

**Issue by dmadisetti** [davidcorbin/euler-offline#2]
How did you extract the text? Your formatting looks great. I think it would be great to have an updated list, which could potentially be coupled with https://github.com/luckytoilet/projecteuler-solutions

**Comment by davidcorbin** [comment]
Honestly not 100% certain how I extracted the text back in 2015. This also may be a better option: https://github.com/imsky/PocketEuler

**Comment by dmadisetti** [comment]
Thanks! I'll take a look at their script, but your outputs still seem cleaner.

![example](https://user-images.githubusercontent.com/2689338/84185294-c8c09980-aa5c-11ea-9bc1-1d4a690ec4b4.png)

I'll close this out once I get something working for reference to others

**Comment by dmadisetti** [comment]
Packaged up nicely in https://www.github.com/dmadisetti/rules_euler
